name: Outputs
run-name: Exemplo workflow para output , executador por ${{ github.actor }}
on: 
    workflow_dispatch:
jobs:
    valores_output:
      runs-on: ubuntu-latest
      steps:
        - name: Output Shell
          id: ex-output
          run: |
            ACTION_RANDOM=$(( $RANDOM ))
            echo action_random=$ACTION_RANDOM >> $GITHUB_OUTPUT
        - name: Exibir output
          run: echo "${{ steps.ex-output.outputs.action_random }}"
