name: Como usar variavel de ambiente e contexto do GitHub Actions
run-name: Exemplo workflow para input, executador por ${{ github.actor }}
on: 
    workflow_dispatch:
      inputs:
        versao:
          type: string
          required: true
          default: "dev"
          description: "Versão release"
        numero_card:
          type: number
          required: true
          description: "Número do card da tarefa desse commit"
        fazer_deploy: 
          type: boolean
          required: true
          description: "Especifica o deploy"
        ambiente:
          type: choice
          required: true
          description: "Ambiente de Deploy"
          options:
            - Desenvolvimento
            - Homologação
            - Produção
jobs:
    valores_input:
      runs-on: ubuntu-latest
      steps:
        - name: Contexto Completo
          run: echo "${{ toJson(inputs) }}"
        - name: Exibindo individualmente
          run: |
            echo "Valores passados nos inputs"
            echo "Versão: ${{ inputs.versao}}"
            echo "Card: ${{ inputs.numero_card }}"
            echo "Deploy: ${{ inputs.fazer_deploy }}"
            echo "Ambiente: ${{ inputs.ambiente }}"


