name: Artifacts
run-name: Estudo Artifact , executador por ${{ github.actor }}
on: 
  workflow_dispatch:
env:
  ARTIFACT_NAME: "artefato-teste"
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: listagem de arquivos
        run: ls
      - name: Gera o artefato
        run: |
          pwd
          echo "Teste de arquivo" >> ./artefatos/arquivo.txt
          echo "Teste de arquivo2" >> ./artefatos/arquivo2.txt
          ls
          pwd
          whoami
      - name: Faz o Upload
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          name: ${{ env.ARTIFACT_NAME }} # nome será usado no download, como vai se repetir use workflowENV
          path: ./artefatos
      - name: Listagem pos upload
        run: ls
      
      - name: output URL dos artefatos
        run: |
          echo "${{ steps.upload-artifact.outputs.artifact-url }}"
  download-artifact:
    runs-on: ubuntu-latest
    needs: [upload-artifact]
    steps:
      - name: Listagem
        run: ls
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }} # precisa ser o mesmo nome do upload
      - name: Listagem pos upload
        run: ls



