name: Outputs
run-name: Exemplo workflow para output , executador por ${{ github.actor }}
on: 
    workflow_dispatch:
jobs:
    valores_output:
      runs-on: ubuntu-latest
      outputs:
        output-shell: ${{ steps.ex-output.outputs.action_random }}
        output-dois: ${{ steps.ex-output.outputs.action_random }}
      steps:
        - name: Output Shell
          id: ex-output
          run: |
            ACTION_RANDOM=$(( $RANDOM ))
            echo action_random=$ACTION_RANDOM >> $GITHUB_OUTPUT
        - name: exibindo outpur
          run: echo "${{ steps.ex-output.outputs.action_random }}"
    exibir_output:
      needs: [valores_output]
      runs-on: ubuntu-latest
      steps:
        - name: exibir valor
          run: |
            echo "${{ needs.valores_output.output-shell }}"
