name: Concorrencia
run-name: Workflow Concorrência ${{ github.run_number }}
on:
    workflow_dispatch:
jobs:
    ex-fluxo-execucao-01:
        runs-on: ubuntu-latest
        steps:
            - name: Execução do job
              run: |
                sleep 120;
                echo "Action Executada"
