name: Execucao-Condicional
on:
    push:
        branches: ["feature"]
jobs:
    apenas_main:
        if: ${{ github.ref == 'refs/heads/main' }}
        name: Só executa na branch main
        runs-on: ubuntu-latest
        steps:
            - name: Executando na main
              run: "echo Executa na Main"
            - name: Verifica o actor
              if: ${{ contains( github.actor, 'Adenilson365') }}
              run: echo "${{ github.actor }} - Adenilson365"