name: Funcoes
on:
  workflow_dispatch:
    inputs:
      actor:
        type: string
        required: true
        default: "Adenilson"
        description: "Nome do Actor"
      numero_card:
        type: number
        required: true
        description: "Número do card da tarefa desse commit"
      fazer_deploy: 
        type: boolean
        required: true
        description: "Especifica o deploy"
      ambiente:
        type: choice
        required: true
        description: "Ambiente de Deploy"
        options:
          - Desenvolvimento
          - Homologação
          - Produção
jobs:
  funcoes_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Função Contains
        run: echo "${{ contains(inputs.actor, github.actor) }}"
      - name: Função Format
        run: "echo ${{ format('String: {0} - Number: {1}', inputs.actor, inputs.numero_card) }}"
      - name: Função Json
        run: echo "${{ toJson(github) }}"
