name: Execucao-Status
on:
    workflow_dispatch:
jobs:
  example_matrix:
    strategy:
      matrix:
        version: [16, 18, 20]
        os: [ubuntu-latest, windows-latest]
    runs-on: "${{ matrix.os }}"
    steps:
        - name: Instalação do node
          uses: actions/setup-node@v4
          with:
            node-version: "${{ matrix.version }}"
        - name: Exibe Versão e OS
          run: |
            node --version
            echo ${{ runner.os }}