name: schedule
on:
    schedule:
        - cron: "*/2 * * * *"
jobs:
    
    imprime:
        runs-on: ubuntu-latest
        steps:
        - name: Imprime uma mensagem
          run:  echo "Mensagem"