name: workflow-dispatch
run-name: Estudo Artifact , executador por ${{ github.actor }}
on: 
  push: 
    branches: [teste]
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: listagem de arquivos
        run: echo "Outro Job"